name: UPM on npsjs.com
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        registry-url: 'https://registry.npmjs.org'
    - run: npm publish
      working-directory: Packages/jp.keijiro.kino.aqua
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    - run: npm publish
      working-directory: Packages/jp.keijiro.kino.aqua.high-definition
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    - run: npm publish
      working-directory: Packages/jp.keijiro.kino.aqua.universal
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
